import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer className="fixed bottom-0 w-full p-1 text-center bg-gray-50">
          <a
            href="https://github.com/J3698/mines"
            target="_blank"
            rel="noopener noreferrer"
            className="text-blue-400 hover:text-blue-800 underline"
          >
            GitHub
          </a>
        </footer>
      </body>
    </html>
  );
}
